### ISSUE TITLE
Criar documento do RichPicture

### ISSUE THREAD

**Issue by joao15victor08** [Requisitos-de-Software/2021.1-Hemovida#7]
### Descrição:
Criar o documento contendo uma explicação sobre o que é RichPicture e o RichPicture do app selecionado

### Critérios de aceitação:
- [x] Esse documento deve conter tabela de versionamento
- [x] Esse documento deve conter as referências bibliográficas

**Comment by LorrayneCardozo** [comment]
O documento do Rich Picture foi criado com todos os atributos exigidos
